
####################################################################################
####################################################################################


# Vivado Generated miscellaneous constraints 

set_property src_info {type:PI file:{} line:-1 export:NONE save:INPUT read:READ} [current_design]
set_property -quiet TOOL_DERIVED_CLK_NAMES {1:0:CLKIN:CLKOUTPHY:mmcm_clkout0:pll_clk[0]} [get_cells -quiet {inst/u_ddr4_phy_pll/plle_loop[0].gen_plle4.PLLE4_BASE_INST_OTHER}]
set_property src_info {type:PI file:{} line:-1 export:NONE save:INPUT read:READ} [current_design]
set_property -quiet TOOL_DERIVED_CLK_NAMES {1:0:CLKIN:CLKOUTPHY:mmcm_clkout0:pll_clk[1]} [get_cells -quiet {inst/u_ddr4_phy_pll/plle_loop[1].gen_plle4.PLLE4_BASE_INST_OTHER}]

####################################################################################
# Constraints from file : 'xilinx_ddr4_ctrl_axi128.xdc'
####################################################################################

set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS12 [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[3]}]

####################################################################################
# Constraints from file : 'ddr4-0.xdc'
####################################################################################

set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG39 [get_ports {ddr4_adr[0]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG40 [get_ports {ddr4_adr[1]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD39 [get_ports {ddr4_adr[2]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE39 [get_ports {ddr4_adr[3]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB39 [get_ports {ddr4_adr[4]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC39 [get_ports {ddr4_adr[5]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF37 [get_ports {ddr4_adr[6]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG37 [get_ports {ddr4_adr[7]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB38 [get_ports {ddr4_adr[8]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC37 [get_ports {ddr4_adr[9]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD37 [get_ports {ddr4_adr[10]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE36 [get_ports {ddr4_adr[11]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF36 [get_ports {ddr4_adr[12]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC36 [get_ports {ddr4_adr[13]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD36 [get_ports {ddr4_adr[14]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF35 [get_ports {ddr4_adr[15]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG35 [get_ports {ddr4_adr[16]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE34 [get_ports {ddr4_ba[0]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE35 [get_ports {ddr4_ba[1]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC35 [get_ports {ddr4_cke[0]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD34 [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF42 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG33 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V42 [get_ports {ddr4_dm_dbi_n[2]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W39 [get_ports {ddr4_dm_dbi_n[3]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB42 [get_ports {ddr4_dq[0]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC42 [get_ports {ddr4_dq[1]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE41 [get_ports {ddr4_dq[2]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF41 [get_ports {ddr4_dq[3]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE40 [get_ports {ddr4_dq[4]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF40 [get_ports {ddr4_dq[5]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB40 [get_ports {ddr4_dq[6]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC40 [get_ports {ddr4_dq[7]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE33 [get_ports {ddr4_dq[8]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF33 [get_ports {ddr4_dq[9]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD32 [get_ports {ddr4_dq[10]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD33 [get_ports {ddr4_dq[11]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE31 [get_ports {ddr4_dq[12]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF31 [get_ports {ddr4_dq[13]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC31 [get_ports {ddr4_dq[14]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD31 [get_ports {ddr4_dq[15]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA41 [get_ports {ddr4_dq[16]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA42 [get_ports {ddr4_dq[17]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W41 [get_ports {ddr4_dq[18]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V41 [get_ports {ddr4_dq[19]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V40 [get_ports {ddr4_dq[20]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U40 [get_ports {ddr4_dq[21]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y39 [get_ports {ddr4_dq[22]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y40 [get_ports {ddr4_dq[23]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U38 [get_ports {ddr4_dq[24]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U39 [get_ports {ddr4_dq[25]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB37 [get_ports {ddr4_dq[26]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA38 [get_ports {ddr4_dq[27]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V37 [get_ports {ddr4_dq[28]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U37 [get_ports {ddr4_dq[29]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA36 [get_ports {ddr4_dq[30]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA37 [get_ports {ddr4_dq[31]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD41 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC41 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC32 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB32 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y41 [get_ports {ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA40 [get_ports {ddr4_dqs_t[2]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W38 [get_ports {ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W37 [get_ports {ddr4_dqs_t[3]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG42 [get_ports {ddr4_odt[0]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC34 [get_ports {ddr4_bg[0]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF32 [get_ports ddr4_reset_n]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG34 [get_ports ddr4_act_n]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG38 [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF38 [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE38 [get_ports sys_clk_n]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD38 [get_ports sys_clk_p]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]

####################################################################################
# Constraints from file : 'config.xdc'
####################################################################################

set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_48 [get_ports sys_clk_p]
